INSERT INTO `labelnew` (`tag`, `lang`, `mode`, `text`) VALUES
('.accidenté', 'en', 'itype', 'injured'),
('.accidenté', 'fr', 'itype', 'accidenté'),
('.blessé', 'en', 'itype', 'wounded'),
('.blessé', 'fr', 'itype', 'blessé'),
('.blessé2', 'en', 'itype', 'wounded'),
('.blessé2', 'fr', 'itype', 'blessé'),
('.capturé', 'en', 'itype', 'captured'),
('.capturé', 'fr', 'itype', 'capturé'),
('.capturé à nouveau', 'en', 'itype', 're-captured'),
('.capturé à nouveau', 'fr', 'itype', 'capturé à nouveau'),
('.déporté', 'en', 'itype', 'deported'),
('.déporté', 'fr', 'itype', 'déporté'),
('.détaché', 'en', 'itype', 'Posted'),
('.détaché', 'fr', 'itype', 'Détaché'),
('.devenu malade', 'en', 'itype', 'became ill'),
('.devenu malade', 'fr', 'itype', 'tombé malade'),
('.disparu', 'en', 'itype', 'disappeared'),
('.disparu', 'fr', 'itype', 'disparu'),
('.évadé', 'en', 'itype', 'escaped'),
('.évadé', 'fr', 'itype', 'évadé'),
('.exécuté', 'en', 'itype', 'executed'),
('.exécuté', 'fr', 'itype', 'exécuté'),
('.libéré', 'en', 'itype', 'freed'),
('.libéré', 'fr', 'itype', 'libéré'),
('.mission', 'en', 'itype', 'mission'),
('.mission', 'fr', 'itype', 'mission'),
('.mort', 'en', 'itype', 'dead'),
('.mort', 'fr', 'itype', 'mort'),
('.muté', 'en', 'itype', 'transfered'),
('.muté', 'fr', 'itype', 'muté'),
('.noyé', 'en', 'itype', 'drowned'),
('.noyé', 'fr', 'itype', 'noyé'),
('.parachuté', 'en', 'itype', 'parachuted'),
('.parachuté', 'fr', 'itype', 'parachuté'),
('.parachuté à nouveau', 'en', 'itype', 're-parachuted'),
('.parachuté à nouveau', 'fr', 'itype', 'parachuté à nouveau'),
('.rejoint', 'en', 'itype', 'rejoined'),
('.rejoint', 'fr', 'itype', 'rejoint'),
('.rentré', 'en', 'itype', 'returned'),
('.rentré', 'fr', 'itype', 'rentre'),
('.retourné', 'en', 'itype', 'returned'),
('.retourné', 'fr', 'itype', 'retourne'),
('.souffrant', 'en', 'itype', 'suffering'),
('.souffrant', 'fr', 'itype', 'souffrant'),
('.transféré', 'en', 'itype', 'transfered'),
('.transféré', 'fr', 'itype', 'transféré'),
('.tué', 'en', 'itype', 'killed'),
('.tué', 'fr', 'itype', 'tué');


