
-- --------------------------------------------------------

--
-- Table structure for table `label`
--

DROP TABLE IF EXISTS `label`;
CREATE TABLE `label` (
  `id` int(11) NOT NULL,
  `tag` varchar(50) NOT NULL,
  `lang` varchar(2) NOT NULL,
  `mode` varchar(10) NOT NULL,
  `text` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `label`
--

INSERT INTO `label` (`id`, `tag`, `lang`, `mode`, `text`) VALUES
(1, '.welcome', 'fr', 'message', 'Bienvenue'),
(2, 'edit.links.for', 'fr', 'message', 'éditer les liens de'),
(3, 'add.new.linkref', 'fr', 'message', 'Créer un lien'),
(4, '.back', 'fr', 'message', 'Retour'),
(5, '.edit', 'fr', 'message', 'éditer'),
(6, '.delete', 'fr', 'message', 'Supprimer'),
(7, 'a.link.from', 'fr', 'message', 'lien de'),
(8, '.submit', 'fr', 'message', 'Envoyez'),
(9, 'edit.this', 'fr', 'message', 'éditer'),
(10, 'create.this', 'fr', 'message', 'Créer ceci'),
(11, '.place', 'fr', 'message', 'Lieu'),
(12, 'bookmark.event', 'fr', 'message', 'signet'),
(13, 'edit.event', 'fr', 'message', 'éditer évènement'),
(14, '.links', 'fr', 'message', 'Liens'),
(15, 'participants', 'fr', 'message', ' __participants'),
(16, 'child.events', 'fr', 'message', 'Sous événements'),
(17, 'event.being.edited', 'fr', 'message', 'Evénement en cours de modification'),
(18, 'edit.event.detail', 'fr', 'message', 'éditer le détail'),
(19, 'delete', 'fr', 'message', ' __delete'),
(20, 'to.add.location.use.bookmarks', 'fr', 'message', 'Pour ajouter un lieu utilisez un signet'),
(21, 'images', 'fr', 'message', ' __images'),
(22, 'to.add.images.use.bookmarks', 'fr', 'message', 'pour ajouter une image, utilisez un signet'),
(23, 'to.add.link.use.bookmarks', 'fr', 'message', 'Pour ajouter un lien utilisez un signet'),
(24, '.texts', 'fr', 'message', 'Textes'),
(25, 'edit.text', 'fr', 'message', 'éditer les textes'),
(26, 'no.text', 'fr', 'message', 'Texte pas encore ajouté'),
(27, 'add.text', 'fr', 'message', 'Ajouter nouveau texte'),
(28, 'to.add.participation.use.bookmarks', 'fr', 'message', 'pour ajouter un participant, utilisez un signet'),
(29, 'edit.event.new', 'fr', 'message', 'Créer nouvel évènement'),
(30, 'new.person', 'fr', 'message', 'Créer un nouveau homme'),
(31, 'Register!', 'fr', 'message', ' __Register!'),
(32, 'edit.person', 'fr', 'message', 'éditer'),
(33, 'create.newperson', 'fr', 'message', 'Créer un Homme'),
(34, 'bookmark.person', 'fr', 'message', 'signet'),
(35, 'print.transcript', 'fr', 'message', 'imprimer copie'),
(36, 'person.a.editer', 'fr', 'message', 'Editer'),
(37, 'participated.in.events', 'fr', 'message', 'Participations'),
(38, 'vue', 'fr', 'message', 'Voir'),
(39, 'entrez.chercher', 'fr', 'message', 'Entrez le mot à chercher'),
(40, 'chercher', 'fr', 'message', 'Chercher'),
(41, 'see.content', 'fr', 'message', 'Voir'),
(42, '.bookmark', 'fr', 'message', 'signet'),
(43, 'remove.bookmarks', 'fr', 'message', 'enlever les signets'),
(44, '.bookmarks', 'fr', 'message', 'signets'),
(45, 'new.book', 'fr', 'message', 'Nouveau Livre'),
(46, 'edit.book', 'fr', 'message', 'Editer'),
(47, 'bibloLinks', 'fr', 'message', 'Livres'),
(48, 'link.visit', 'fr', 'message', 'Voir Lien'),
(49, 'bookmark.link', 'fr', 'message', 'signet'),
(50, '.book', 'fr', 'message', 'Livre'),
(51, 'edit.book.detail', 'fr', 'message', 'éditer le livre'),
(52, 'book.title', 'fr', 'message', 'Titre'),
(53, 'book.subtitle', 'fr', 'message', 'Sous-titre'),
(54, 'book.author', 'fr', 'message', 'Auteur'),
(55, 'book.publisher', 'fr', 'message', 'Éditeur'),
(56, 'book.year', 'fr', 'message', 'année'),
(57, 'book.isbn', 'fr', 'message', 'ISBN'),
(58, '.reset', 'fr', 'message', 'réinitialiser'),
(59, 'see.location', 'fr', 'message', 'Voir'),
(60, 'edit.location', 'fr', 'message', 'éditer l\'endroit'),
(61, 'child.of', 'fr', 'message', 'Enfant de'),
(62, 'location.a.editer', 'fr', 'message', 'Editer Location'),
(63, 'new.location', 'fr', 'message', 'Nouvel endroit'),
(64, '.introduction', 'fr', 'message', 'Introduction'),
(65, 'our.site', 'fr', 'message', 'Notre site FFLSAS'),
(66, 'the.men', 'fr', 'message', 'Les hommes'),
(67, 'the.action', 'fr', 'message', ' __the.action'),
(68, 'search.site', 'fr', 'message', 'Chercher dans le site'),
(69, 'user.profile', 'fr', 'message', ' __user.profile'),
(70, 'admin.images', 'fr', 'message', 'Gérer Images'),
(71, 'admin.locations', 'fr', 'message', 'Gérer Locations'),
(72, 'admin.content', 'fr', 'message', 'Gérer Contenu'),
(73, 'admin.allusers', 'fr', 'message', 'Gérer Utilisateurs'),
(74, 'admin.messages', 'fr', 'message', 'Message de l\'administrateur'),
(75, 'new.incident', 'fr', 'message', 'nouvel incident'),
(76, 'edit.incident', 'fr', 'message', 'éditer incident'),
(77, 'create.new.incident.type', 'fr', 'message', ' __create.new.incident.type'),
(78, 'incident.to', 'fr', 'message', 'Incident dans le parcours de'),
(79, '.during', 'fr', 'message', 'pendant'),
(80, 'the.campaign', 'fr', 'message', 'la campagne'),
(81, 'he.was', 'fr', 'message', 'il a été'),
(82, 'under.the.name.of', 'fr', 'message', 'nommé'),
(83, 'with.the.role.of', 'fr', 'message', ' __with.the.role.of'),
(84, '.at', 'fr', 'message', 'à'),
(85, '.view', 'fr', 'message', ' __.view'),
(86, 'on.date', 'fr', 'message', 'le'),
(87, 'incident.rank', 'fr', 'message', 'avec le grade de'),
(88, 'incident.role', 'fr', 'message', 'rôle'),
(89, 'browse.locations', 'fr', 'message', 'Naviguer vers les lieux'),
(90, 'les.livres', 'fr', 'message', 'Gérer les livres'),
(91, 'the.links', 'fr', 'message', 'Les Liens'),
(92, 'admin.labels', 'fr', 'message', 'Gerer étiquettes'),
(93, 'make.roh', 'fr', 'message', 'Export Rôle d\'Honneur'),
(94, 'make.actions', 'fr', 'message', 'Export Evenements'),
(95, 'move.new.images', 'fr', 'message', 'Transferer Les Images'),
(96, 'admin.privacy', 'fr', 'message', 'politique de confidentialité'),
(97, 'request.new.password', 'fr', 'message', 'Demander un nouveau mot de passe'),
(98, 'await.stage2', 'fr', 'message', 'Apres vérification par l\'administrateur vous recevrez un email'),
(99, '.username', 'fr', 'message', 'Nom de l\'utilisateur'),
(100, '.email', 'fr', 'message', 'Adresse email'),
(101, 'sucessful.completion', 'fr', 'message', 'inscription réussie'),
(102, '.reconnect', 'fr', 'message', 'Se déconnecter puis se reconnecter pour continuer comme utilisateur'),
(103, '.register', 'fr', 'message', 's\'inscrire'),
(104, 'complete.registration', 'fr', 'message', 'terminer le processus d\'inscription'),
(105, 'admin.has.sent.a.message.to', 'fr', 'message', 'Admin a envoyé un message à'),
(106, 'message.sent.by', 'fr', 'message', 'envoyé par'),
(107, 'message.date', 'fr', 'message', 'envoyé le'),
(108, 'message.subject', 'fr', 'message', 'sujet'),
(109, 'send.bulk.message', 'fr', 'message', 'Envoyer un message à plusieurs utilisateurs'),
(110, 'message.forwarded.by.admin', 'fr', 'message', 'de FFLSAS-admin'),
(111, 'message.to', 'fr', 'message', 'envoyé à'),
(112, '.recepients', 'fr', 'message', 'destinataires'),
(113, '.send', 'fr', 'message', 'envoyer'),
(114, 'message.enyoyer.a', 'fr', 'message', 'destinataire'),
(115, 'mail.date.sent', 'fr', 'message', 'envoyé le'),
(116, 'mail.sentby', 'fr', 'message', 'envoyé par'),
(117, 'mail.from', 'fr', 'message', 'de'),
(118, 'mail.subject', 'fr', 'message', 'sujet'),
(119, 'read.message', 'fr', 'message', 'Lire message'),
(120, 'delete.message', 'fr', 'message', 'Suprimer'),
(121, 'message.bcc', 'fr', 'message', 'des copies cachées'),
(122, 'contact.us', 'fr', 'message', 'Nous envoyer un message ou poser une question'),
(123, 'see.admin.messages', 'fr', 'message', 'Messagerie'),
(124, 'message.list', 'fr', 'message', 'liste des messages'),
(125, 'from.admin.to', 'fr', 'message', 'a'),
(126, '.from', 'fr', 'message', 'de'),
(127, 'view.message', 'fr', 'message', 'voir'),
(128, 'message.enyoyer', 'fr', 'message', 'message envoyé'),
(129, 'mail.body', 'fr', 'message', 'Contenu'),
(130, 'many.users', 'fr', 'message', 'plusieurs utilisateurs'),
(131, 'this.message.was.sent.by', 'fr', 'message', 'message envoyé par'),
(132, 'message.to.user', 'fr', 'message', 'Message a l\'utilisateur'),
(133, 'you.have.sent.a.message.to.FFLSAS.org', 'fr', 'message', 'Vous avez envoyé un message à FFLSAS.org'),
(134, 'a.copy.has.been.sent.to.your.email.address', 'fr', 'message', 'Une copie a été envoyée à votre adresse email.'),
(135, 'bookmark.content', 'fr', 'message', 'marquer'),
(136, 'edit.content', 'fr', 'message', 'éditer'),
(137, 'links.to', 'fr', 'message', 'Liens vers'),
(138, 'edit.contents', 'fr', 'message', 'modifier'),
(139, 'FR', 'fr', 'message', 'FR'),
(140, 'EN', 'fr', 'message', 'EN'),
(141, 'content.for.subject', 'fr', 'message', 'sujet'),
(142, 'voir', 'fr', 'message', ' __voir'),
(143, 'delete.content', 'fr', 'message', 'supprimer'),
(144, 'new.content', 'fr', 'message', 'Nouveau contenu'),
(145, '.subjectid', 'fr', 'message', ' __.subjectid'),
(146, '.language', 'fr', 'message', 'Langue préférée'),
(147, '.title', 'fr', 'message', 'Titre'),
(148, '.public', 'fr', 'message', 'publique'),
(149, '.admin', 'fr', 'message', 'Admin'),
(150, '.private', 'fr', 'message', 'privé'),
(151, 'click.me', 'fr', 'message', 'Envoyez'),
(152, '.adminstrators', 'fr', 'message', 'Administrateurs'),
(153, 'linked.from', 'fr', 'message', 'Lien de'),
(154, 'the.events', 'fr', 'message', 'Leurs actions'),
(155, 'see.links', 'fr', 'message', 'Voir les liens'),
(156, 'see.books', 'fr', 'message', 'Quelques livres'),
(157, 'user.show', 'fr', 'message', 'Profil de l\'utilisateur'),
(158, 'login.message', 'fr', 'message', 'Pour accéder à notre site, identifiez-vous'),
(159, '.password', 'fr', 'message', 'Mot de passe'),
(160, 'if.password.forgotten', 'fr', 'message', 'mot de passe oublié'),
(161, 'reset.password', 'fr', 'message', 'réinitialiser le mot de passe'),
(162, 'if.not.registered', 'fr', 'message', 'Pas encore enregistré'),
(163, 'search.results', 'fr', 'message', 'Resultats de recherche pour'),
(164, 'found.too.many', 'fr', 'message', 'Trop trouvé'),
(165, 'found', 'fr', 'message', 'Trouvé'),
(166, 'welcome.page', 'fr', 'message', 'Page d\'accueil'),
(167, '.count', 'fr', 'message', ' __.count'),
(168, 'latest.edits', 'fr', 'message', 'Dernières mises à jour'),
(169, 'update.translation.files', 'fr', 'message', 'mettre à jour les fichiers de traduction'),
(170, 'new.label', 'fr', 'message', 'Créer une nouvelle étiquette'),
(171, 'profil.person', 'fr', 'message', 'profil de l\'utilisateur'),
(172, 'edit.user.detail', 'fr', 'message', 'Modifier'),
(173, 'user.email', 'fr', 'message', 'Adresse e-mail'),
(174, 'user.roles', 'fr', 'message', 'Rôles d\'utilisateur'),
(175, 'user.lastlogin', 'fr', 'message', 'Dernier accès'),
(176, 'send.message', 'fr', 'message', 'Envoyer un message'),
(177, 'user.membership', 'fr', 'message', 'Grade du membre'),
(178, 'user.locale', 'fr', 'message', 'Langue préférée'),
(179, 'user.to.admin', 'fr', 'message', 'à l\'administrateur'),
(180, 'admin.to.user', 'fr', 'message', 'à l\'utilisateur'),
(181, 'new.user', 'fr', 'message', 'nouvel utilisateur'),
(182, 'users.for.approval', 'fr', 'message', 'Utilisateurs pour approbation'),
(183, 'see.user', 'fr', 'message', 'Voir Utilisateur'),
(184, 'bulk.message', 'fr', 'message', 'message à plusieurs utilisateurs'),
(185, 'to.send.bulk.email.use.bookmarks', 'fr', 'message', 'Pour envoyer des e-mails en masse, utilisez un signet.'),
(186, 'rereg.group', 'fr', 'message', 'Re-enregistrer un groupe'),
(187, 'edit.user', 'fr', 'message', 'editer utilisateur'),
(188, 'message.sentby', 'fr', 'message', 'message de'),
(189, 'enter.new.password', 'fr', 'message', 'Nouveau mot de passe'),
(190, '.users', 'fr', 'message', 'utiisateurs'),
(191, 'view.user', 'fr', 'message', 'view.user'),
(192, 'delete.user', 'fr', 'message', 'supprimer'),
(193, 'approve.user', 'fr', 'message', 'Approuver'),
(194, 'reject.user', 'fr', 'message', 'Reject'),
(195, 'rereg.user', 'fr', 'message', 'ré-enregistrer un utilisateur'),
(196, 'user.interet', 'fr', 'message', 'Interet du membre'),
(197, '.contributor', 'fr', 'message', 'Administrateur'),
(198, 'user.update_dt', 'fr', 'message', 'Date révisé'),
(199, 'delete.messages', 'fr', 'message', 'Supprimer les messages'),
(200, 'to.admin', 'fr', 'message', 'a ADMIN'),
(201, 'from.admin', 'fr', 'message', 'De ADMIN'),
(202, '.message', 'fr', 'message', 'Message'),
(203, 'forced.registration', 'fr', 'message', 'Demander une réinscription'),
(204, 'new.image', 'fr', 'message', 'Nouvelle Image'),
(205, 'bookmark.image', 'fr', 'message', 'signet'),
(206, 'see.image', 'fr', 'message', 'voir'),
(207, 'create.edit.image', 'fr', 'message', 'Créer ou éditer une image'),
(208, 'create.image', 'fr', 'message', 'Créer une image'),
(209, 'edit.image', 'fr', 'message', 'éditer'),
(210, 'edit.texts', 'fr', 'message', 'éditer les textes'),
(211, 'delete.image', 'fr', 'message', 'supprimer l\'image'),
(212, '.urlinks', 'fr', 'message', 'Liens'),
(213, 'new.link', 'fr', 'message', 'créer un lien'),
(214, 'edit.link', 'fr', 'message', 'éditer le lien'),
(215, 'delete.link', 'fr', 'message', 'supprimer'),
(216, 'a.link.to', 'fr', 'message', 'Lien a'),
(217, '.url', 'fr', 'message', 'URL'),
(218, '.tags', 'fr', 'message', 'Étiquettes'),
(219, '.visit', 'fr', 'message', 'Visiter'),
(220, 'new.url', 'fr', 'message', 'créer un URL'),
(221, 'edit', 'fr', 'message', ' __edit'),
(222, 'for', 'fr', 'message', ' __for'),
(223, '.for', 'fr', 'message', 'pour'),
(224, 'delete.this', 'fr', 'message', 'supprimer ceci'),
(225, 'this.is.an.edit', 'fr', 'message', 'Ceci est une edition'),
(226, '.infrench', 'fr', 'message', 'In English'),
(227, '.inenglish', 'fr', 'message', 'Show the site in English'),
(228, 'welcome.guest', 'fr', 'message', 'Bienvenue au visiteur'),
(229, 'awaiting.approval', 'fr', 'message', ' __awaiting.approval'),
(230, 'friend', 'fr', 'message', 'Ami'),
(231, 'complete.reg', 'fr', 'message', 'compléter l\'inscription'),
(232, 'log.in', 'fr', 'message', 'S\'identifier'),
(233, 'log.out', 'fr', 'message', 'Se déconnecter'),
(234, 'mail.us', 'fr', 'message', 'Nous envoyer un message'),
(235, 'edit.participation', 'fr', 'message', 'éditer'),
(236, 'create.incident', 'fr', 'message', 'Créer un incident'),
(237, 'incidents', 'fr', 'message', ' __incidents'),
(238, 'edit.participations', 'fr', 'message', 'éditer'),
(239, 'image.chance', 'fr', 'message', 'Image au hasard'),
(240, '.welcome', 'en', 'message', 'Welcome'),
(241, 'edit.links.for', 'en', 'message', 'Edit links'),
(242, 'add.new.linkref', 'en', 'message', 'Create new Link'),
(243, '.back', 'en', 'message', 'Cancel'),
(244, '.edit', 'en', 'message', 'Edit'),
(245, '.delete', 'en', 'message', 'Delete'),
(246, 'a.link.from', 'en', 'message', 'Link from'),
(247, '.submit', 'en', 'message', 'Send'),
(248, 'edit.this', 'en', 'message', 'Edit'),
(249, 'create.this', 'en', 'message', 'Create this'),
(250, '.place', 'en', 'message', 'Location'),
(251, 'bookmark.event', 'en', 'message', 'bookmark'),
(252, 'edit.event', 'en', 'message', 'Edit event'),
(253, '.links', 'en', 'message', 'Links'),
(254, 'participants', 'en', 'message', ' __participants'),
(255, 'child.events', 'en', 'message', 'Sub-events'),
(256, 'event.being.edited', 'en', 'message', 'Event being edited'),
(257, 'edit.event.detail', 'en', 'message', 'Edit detail'),
(258, 'delete', 'en', 'message', ' __delete'),
(259, 'to.add.location.use.bookmarks', 'en', 'message', 'To add a location use a bookmark'),
(260, 'images', 'en', 'message', ' __images'),
(261, 'to.add.images.use.bookmarks', 'en', 'message', 'To add images use bookmarks.'),
(262, 'to.add.link.use.bookmarks', 'en', 'message', 'To add a link use a bookmark'),
(263, '.texts', 'en', 'message', 'Texts'),
(264, 'edit.text', 'en', 'message', 'Edit texts'),
(265, 'no.text', 'en', 'message', 'No texts added yet'),
(266, 'add.text', 'en', 'message', 'Add a new text'),
(267, 'to.add.participation.use.bookmarks', 'en', 'message', 'To add a participant use a bookmark'),
(268, 'edit.event.new', 'en', 'message', 'Create New Event'),
(269, 'new.person', 'en', 'message', 'Create a new Man'),
(270, 'Register!', 'en', 'message', ' __Register!'),
(271, 'edit.person', 'en', 'message', 'Edit'),
(272, 'create.newperson', 'en', 'message', 'Create a Person'),
(273, 'bookmark.person', 'en', 'message', 'bookmark'),
(274, 'print.transcript', 'en', 'message', 'print copy'),
(275, 'person.a.editer', 'en', 'message', 'Editing'),
(276, 'participated.in.events', 'en', 'message', 'Participations'),
(277, 'vue', 'en', 'message', 'See'),
(278, 'entrez.chercher', 'en', 'message', 'Enter Search Term'),
(279, 'chercher', 'en', 'message', 'Search'),
(280, 'see.content', 'en', 'message', 'See'),
(281, '.bookmark', 'en', 'message', 'bookmark'),
(282, 'remove.bookmarks', 'en', 'message', 'Remove .bookmarks'),
(283, '.bookmarks', 'en', 'message', 'bookmarks'),
(284, 'new.book', 'en', 'message', 'New Book'),
(285, 'edit.book', 'en', 'message', 'Edit'),
(286, 'bibloLinks', 'en', 'message', 'Books'),
(287, 'link.visit', 'en', 'message', 'Visit'),
(288, 'bookmark.link', 'en', 'message', 'Bookmark link'),
(289, '.book', 'en', 'message', 'Book'),
(290, 'edit.book.detail', 'en', 'message', 'Edit Book'),
(291, 'book.title', 'en', 'message', 'Title'),
(292, 'book.subtitle', 'en', 'message', 'Subtitle'),
(293, 'book.author', 'en', 'message', 'Author'),
(294, 'book.publisher', 'en', 'message', 'Publisher'),
(295, 'book.year', 'en', 'message', 'Year'),
(296, 'book.isbn', 'en', 'message', 'ISBN'),
(297, '.reset', 'en', 'message', 'clear'),
(298, 'see.location', 'en', 'message', 'See'),
(299, 'edit.location', 'en', 'message', 'Edit location'),
(300, 'child.of', 'en', 'message', 'Child of'),
(301, 'location.a.editer', 'en', 'message', 'Edit location'),
(302, 'new.location', 'en', 'message', 'New Location'),
(303, '.introduction', 'en', 'message', 'Introduction'),
(304, 'our.site', 'en', 'message', 'Our site FFLSAS'),
(305, 'the.men', 'en', 'message', 'The Men'),
(306, 'the.action', 'en', 'message', ' __the.action'),
(307, 'search.site', 'en', 'message', 'Search the site'),
(308, 'user.profile', 'en', 'message', ' __user.profile'),
(309, 'admin.images', 'en', 'message', 'Edit images'),
(310, 'admin.locations', 'en', 'message', 'Edit locations'),
(311, 'admin.content', 'en', 'message', 'Edit Content'),
(312, 'admin.allusers', 'en', 'message', 'Edit Users'),
(313, 'admin.messages', 'en', 'message', 'Message to ADMIN'),
(314, 'new.incident', 'en', 'message', 'New incident'),
(315, 'edit.incident', 'en', 'message', 'Edit incident'),
(316, 'create.new.incident.type', 'en', 'message', ' __create.new.incident.type'),
(317, 'incident.to', 'en', 'message', 'Incident in the service of ='),
(318, '.during', 'en', 'message', 'during'),
(319, 'the.campaign', 'en', 'message', 'the campaign'),
(320, 'he.was', 'en', 'message', 'he was'),
(321, 'under.the.name.of', 'en', 'message', 'under the name of'),
(322, 'with.the.role.of', 'en', 'message', ' __with.the.role.of'),
(323, '.at', 'en', 'message', 'at'),
(324, '.view', 'en', 'message', ' __.view'),
(325, 'on.date', 'en', 'message', 'the'),
(326, 'incident.rank', 'en', 'message', 'with the rank of'),
(327, 'incident.role', 'en', 'message', 'role'),
(328, 'browse.locations', 'en', 'message', 'Browse locations'),
(329, 'les.livres', 'en', 'message', 'Books'),
(330, 'the.links', 'en', 'message', 'Our Links'),
(331, 'admin.labels', 'en', 'message', 'Manage Labels'),
(332, 'make.roh', 'en', 'message', 'Export Role Of Honour'),
(333, 'make.actions', 'en', 'message', 'Export Actions'),
(334, 'move.new.images', 'en', 'message', 'Transfer Images'),
(335, 'admin.privacy', 'en', 'message', 'Privacy'),
(336, 'request.new.password', 'en', 'message', 'Request a new password'),
(337, 'await.stage2', 'en', 'message', ' __await.stage2'),
(338, '.username', 'en', 'message', 'Username'),
(339, '.email', 'en', 'message', 'Email Address'),
(340, 'sucessful.completion', 'en', 'message', 'Registartion successful'),
(341, '.reconnect', 'en', 'message', 'Logout and Login again to continue as user'),
(342, '.register', 'en', 'message', 'Register'),
(343, 'complete.registration', 'en', 'message', 'Complete registration'),
(344, 'admin.has.sent.a.message.to', 'en', 'message', 'Admin has sent a message to'),
(345, 'message.sent.by', 'en', 'message', 'sent by'),
(346, 'message.date', 'en', 'message', 'date sent'),
(347, 'message.subject', 'en', 'message', 'subject'),
(348, 'send.bulk.message', 'en', 'message', 'Send a message to multiple users'),
(349, 'message.forwarded.by.admin', 'en', 'message', 'forwarded by FFLSAS-admin'),
(350, 'message.to', 'en', 'message', 'sent to'),
(351, '.recepients', 'en', 'message', 'recepients'),
(352, '.send', 'en', 'message', 'send'),
(353, 'message.enyoyer.a', 'en', 'message', 'destination'),
(354, 'mail.date.sent', 'en', 'message', 'message sent on'),
(355, 'mail.sentby', 'en', 'message', 'message sent by'),
(356, 'mail.from', 'en', 'message', 'message fropm'),
(357, 'mail.subject', 'en', 'message', 'subject'),
(358, 'read.message', 'en', 'message', 'Read message'),
(359, 'delete.message', 'en', 'message', 'Delete message'),
(360, 'message.bcc', 'en', 'message', 'Blind Copies'),
(361, 'contact.us', 'en', 'message', 'Send us a message or ask a question'),
(362, 'see.admin.messages', 'en', 'message', 'Admin messages'),
(363, 'message.list', 'en', 'message', 'List of messages'),
(364, 'from.admin.to', 'en', 'message', 'to'),
(365, '.from', 'en', 'message', 'from'),
(366, 'view.message', 'en', 'message', 'Read message'),
(367, 'message.enyoyer', 'en', 'message', 'message sent'),
(368, 'mail.body', 'en', 'message', 'Message'),
(369, 'many.users', 'en', 'message', 'Many users'),
(370, 'this.message.was.sent.by', 'en', 'message', 'This message was sent by'),
(371, 'message.to.user', 'en', 'message', 'Message to USER'),
(372, 'you.have.sent.a.message.to.FFLSAS.org', 'en', 'message', 'You have sent a message to FFLSAS.og'),
(373, 'a.copy.has.been.sent.to.your.email.address', 'en', 'message', 'A copy has been sent to your email address'),
(374, 'bookmark.content', 'en', 'message', 'bookmark content'),
(375, 'edit.content', 'en', 'message', 'Edit Content'),
(376, 'links.to', 'en', 'message', 'Links to'),
(377, 'edit.contents', 'en', 'message', 'edit contents'),
(378, 'FR', 'en', 'message', 'FR'),
(379, 'EN', 'en', 'message', 'EN'),
(380, 'content.for.subject', 'en', 'message', 'subject'),
(381, 'voir', 'en', 'message', ' __voir'),
(382, 'delete.content', 'en', 'message', 'delete content'),
(383, 'new.content', 'en', 'message', 'New Content'),
(384, '.subjectid', 'en', 'message', ' __.subjectid'),
(385, '.language', 'en', 'message', 'Prefered language'),
(386, '.title', 'en', 'message', 'Title'),
(387, '.public', 'en', 'message', 'public'),
(388, '.admin', 'en', 'message', 'Admin'),
(389, '.private', 'en', 'message', 'private'),
(390, 'click.me', 'en', 'message', 'Send'),
(391, '.adminstrators', 'en', 'message', 'Administrators'),
(392, 'linked.from', 'en', 'message', 'Linked from'),
(393, 'the.events', 'en', 'message', 'The Action'),
(394, 'see.links', 'en', 'message', 'Our Links'),
(395, 'see.books', 'en', 'message', 'See our library'),
(396, 'user.show', 'en', 'message', 'User Profile'),
(397, 'login.message', 'en', 'message', 'To access all of our site sign in.'),
(398, '.password', 'en', 'message', 'Password'),
(399, 'if.password.forgotten', 'en', 'message', 'Password Forgotten'),
(400, 'reset.password', 'en', 'message', 'reset password'),
(401, 'if.not.registered', 'en', 'message', 'To register'),
(402, 'search.results', 'en', 'message', 'Results of search for'),
(403, 'found.too.many', 'en', 'message', 'Too many found'),
(404, 'found', 'en', 'message', 'Found'),
(405, 'welcome.page', 'en', 'message', 'Home Page'),
(406, '.count', 'en', 'message', ' __.count'),
(407, 'latest.edits', 'en', 'message', 'Latest Updates'),
(408, 'update.translation.files', 'en', 'message', 'update the translation files'),
(409, 'new.label', 'en', 'message', 'Create new Label'),
(410, 'profil.person', 'en', 'message', 'User profile'),
(411, 'edit.user.detail', 'en', 'message', 'edit user'),
(412, 'user.email', 'en', 'message', 'user email'),
(413, 'user.roles', 'en', 'message', 'User roles'),
(414, 'user.lastlogin', 'en', 'message', 'Last login'),
(415, 'send.message', 'en', 'message', 'Send message'),
(416, 'user.membership', 'en', 'message', 'User Level'),
(417, 'user.locale', 'en', 'message', 'Prefered language'),
(418, 'user.to.admin', 'en', 'message', 'User to Admin'),
(419, 'admin.to.user', 'en', 'message', 'Admin to User'),
(420, 'new.user', 'en', 'message', 'New user'),
(421, 'users.for.approval', 'en', 'message', 'Users for approval'),
(422, 'see.user', 'en', 'message', 'View User'),
(423, 'bulk.message', 'en', 'message', 'Bulk message'),
(424, 'to.send.bulk.email.use.bookmarks', 'en', 'message', 'To send bulk email use a bookmark'),
(425, 'rereg.group', 'en', 'message', 'Reregister a group'),
(426, 'edit.user', 'en', 'message', 'Edit user'),
(427, 'message.sentby', 'en', 'message', 'Message sent by'),
(428, 'enter.new.password', 'en', 'message', 'Enter new password'),
(429, '.users', 'en', 'message', 'users'),
(430, 'view.user', 'en', 'message', 'See user'),
(431, 'delete.user', 'en', 'message', 'delete user'),
(432, 'approve.user', 'en', 'message', 'Approve'),
(433, 'reject.user', 'en', 'message', 'Rejeter'),
(434, 'rereg.user', 'en', 'message', 're-register user'),
(435, 'user.interet', 'en', 'message', 'Member interest'),
(436, '.contributor', 'en', 'message', 'Administrator'),
(437, 'user.update_dt', 'en', 'message', 'Date Changed'),
(438, 'delete.messages', 'en', 'message', 'Delete messages'),
(439, 'to.admin', 'en', 'message', 'To ADMIN'),
(440, 'from.admin', 'en', 'message', 'From ADMIN'),
(441, '.message', 'en', 'message', 'Message'),
(442, 'forced.registration', 'en', 'message', 'Force re-registration'),
(443, 'new.image', 'en', 'message', 'New Image'),
(444, 'bookmark.image', 'en', 'message', 'Bookmark image'),
(445, 'see.image', 'en', 'message', 'See image'),
(446, 'create.edit.image', 'en', 'message', 'Create or Edit Image'),
(447, 'create.image', 'en', 'message', 'Create image'),
(448, 'edit.image', 'en', 'message', 'Edit image'),
(449, 'edit.texts', 'en', 'message', 'Edit texts'),
(450, 'delete.image', 'en', 'message', 'Delete Image'),
(451, '.urlinks', 'en', 'message', 'Links'),
(452, 'new.link', 'en', 'message', 'New Link'),
(453, 'edit.link', 'en', 'message', 'Edit Link'),
(454, 'delete.link', 'en', 'message', 'Delete Link'),
(455, 'a.link.to', 'en', 'message', 'Link To'),
(456, '.url', 'en', 'message', 'URL'),
(457, '.tags', 'en', 'message', 'Tags'),
(458, '.visit', 'en', 'message', 'Visit'),
(459, 'new.url', 'en', 'message', 'New Url Link'),
(460, 'edit', 'en', 'message', ' __edit'),
(461, 'for', 'en', 'message', ' __for'),
(462, '.for', 'en', 'message', 'for'),
(463, 'delete.this', 'en', 'message', 'Delete'),
(464, 'this.is.an.edit', 'en', 'message', 'This is an edit'),
(465, '.infrench', 'en', 'message', 'En Francais'),
(466, '.inenglish', 'en', 'message', 'Show site in English'),
(467, 'welcome.guest', 'en', 'message', 'Welcome visitor'),
(468, 'awaiting.approval', 'en', 'message', ' __awaiting.approval'),
(469, 'friend', 'en', 'message', 'Friend'),
(470, 'complete.reg', 'en', 'message', 'Complete registration'),
(471, 'log.in', 'en', 'message', 'Log In'),
(472, 'log.out', 'en', 'message', 'Log Out'),
(473, 'mail.us', 'en', 'message', 'Send us a message'),
(474, 'edit.participation', 'en', 'message', 'Edit'),
(475, 'create.incident', 'en', 'message', 'Create an incident'),
(476, 'incidents', 'en', 'message', ' __incidents'),
(477, 'edit.participations', 'en', 'message', 'Edit'),
(478, 'image.chance', 'en', 'message', 'Lucky Image'),
(479, '.accidenté', 'en', 'itype', 'injured'),
(480, '.accidenté', 'fr', 'itype', 'accidenté'),
(481, '.blessé', 'en', 'itype', 'wounded'),
(482, '.blessé', 'fr', 'itype', 'blessé'),
(483, '.blessé2', 'en', 'itype', 'wounded'),
(484, '.blessé2', 'fr', 'itype', 'blessé'),
(485, '.capturé', 'en', 'itype', 'captured'),
(486, '.capturé', 'fr', 'itype', 'capturé'),
(487, '.capturé à nouveau', 'en', 'itype', 're-captured'),
(488, '.capturé à nouveau', 'fr', 'itype', 'capturé à nouveau'),
(489, '.déporté', 'en', 'itype', 'deported'),
(490, '.déporté', 'fr', 'itype', 'déporté'),
(491, '.détaché', 'en', 'itype', 'Posted'),
(492, '.détaché', 'fr', 'itype', 'Détaché'),
(493, '.devenu malade', 'en', 'itype', 'became ill'),
(494, '.devenu malade', 'fr', 'itype', 'tombé malade'),
(495, '.disparu', 'en', 'itype', 'disappeared'),
(496, '.disparu', 'fr', 'itype', 'disparu'),
(497, '.évadé', 'en', 'itype', 'escaped'),
(498, '.évadé', 'fr', 'itype', 'évadé'),
(499, '.exécuté', 'en', 'itype', 'executed'),
(500, '.exécuté', 'fr', 'itype', 'exécuté'),
(501, '.libéré', 'en', 'itype', 'freed'),
(502, '.libéré', 'fr', 'itype', 'libéré'),
(503, '.mission', 'en', 'itype', 'mission'),
(504, '.mission', 'fr', 'itype', 'mission'),
(505, '.mort', 'en', 'itype', 'dead'),
(506, '.mort', 'fr', 'itype', 'mort'),
(507, '.muté', 'en', 'itype', 'transfered'),
(508, '.muté', 'fr', 'itype', 'muté'),
(509, '.noyé', 'en', 'itype', 'drowned'),
(510, '.noyé', 'fr', 'itype', 'noyé'),
(511, '.parachuté', 'en', 'itype', 'parachuted'),
(512, '.parachuté', 'fr', 'itype', 'parachuté'),
(513, '.parachuté à nouveau', 'en', 'itype', 're-parachuted'),
(514, '.parachuté à nouveau', 'fr', 'itype', 'parachuté à nouveau'),
(515, '.rejoint', 'en', 'itype', 'rejoined'),
(516, '.rejoint', 'fr', 'itype', 'rejoint'),
(517, '.rentré', 'en', 'itype', 'returned'),
(518, '.rentré', 'fr', 'itype', 'rentre'),
(519, '.retourné', 'en', 'itype', 'returned'),
(520, '.retourné', 'fr', 'itype', 'retourne'),
(521, '.souffrant', 'en', 'itype', 'suffering'),
(522, '.souffrant', 'fr', 'itype', 'souffrant'),
(523, '.transféré', 'en', 'itype', 'transfered'),
(524, '.transféré', 'fr', 'itype', 'transféré'),
(525, '.tué', 'en', 'itype', 'killed'),
(526, '.tué', 'fr', 'itype', 'tué'),
(527, 'translation.files.produced', 'fr', 'message', 'fichiers de traduction produits'),
(528, 'translation.files.produced', 'en', 'message', 'translation files produced'),
(531, 'search.the.men', 'fr', 'message', 'Chercher les hommes'),
(532, 'search.the.men', 'en', 'message', 'Search the Men'),
(533, 'entrer.search', 'fr', 'message', 'Entrer Mot a chercher'),
(534, 'entrer.search', 'en', 'message', 'Enter Search Term'),
(535, 'found.with', 'fr', 'message', 'Trouvé avec'),
(536, 'found.with', 'en', 'message', 'Found with'),
(537, '.search', 'fr', 'message', 'Chercher'),
(538, '.search', 'en', 'message', 'Search'),
(539, 'rien.a.chercher', 'fr', 'message', 'Rien a chercher'),
(540, 'rien.a.chercher', 'en', 'message', 'Nothing to search for'),
(541, '.toname', 'fr', 'message', 'Destinataire'),
(542, '.toname', 'en', 'message', 'Receiver'),
(543, '.fromname', 'fr', 'message', 'Envoyer'),
(544, '.fromname', 'en', 'message', 'Sender'),
(545, '.fromemail', 'fr', 'message', 'Email Envoyeur'),
(546, '.fromemail', 'en', 'message', 'Sender Email'),
(547, '.subject', 'fr', 'message', 'Sujet'),
(548, '.subject', 'en', 'message', 'Subject'),
(549, '.body', 'fr', 'message', 'Contenu'),
(550, '.body', 'en', 'message', 'Message'),
(551, 'found.all', 'fr', 'message', 'Tout trouvé'),
(552, 'found.all', 'en', 'message', 'All found'),
(553, 'enter.search', 'fr', 'message', 'Entrer Mot a chercher'),
(554, 'enter.search', 'en', 'message', 'Enter Search Term'),
(555, 'manage.images', 'fr', 'message', 'Gérer les images'),
(556, 'manage.images', 'en', 'message', 'Manage images'),
(557, '.imagename', 'fr', 'message', 'Libelle'),
(558, '.imagename', 'en', 'message', 'Label'),
(559, '.path', 'fr', 'message', 'Chemin du fichier'),
(560, '.path', 'en', 'message', 'File path'),
(561, '.copyright', 'fr', 'message', 'Droits d\'auteur'),
(562, '.copyright', 'en', 'message', 'Copyright'),
(563, '.format', 'fr', 'message', 'Format de fichier'),
(564, '.format', 'en', 'message', 'File format'),
(565, '.access', 'fr', 'message', 'Accès'),
(566, '.access', 'en', 'message', 'Access'),
(567, 'image.file', 'fr', 'message', 'Fichier d\'image'),
(568, 'image.file', 'en', 'message', 'Image file'),
(569, 'location.name', 'fr', 'message', 'Nom de lieu'),
(570, 'location.name', 'en', 'message', 'Place name'),
(571, '.region', 'fr', 'message', 'Région'),
(572, '.region', 'en', 'message', 'Region'),
(573, '.latitude', 'fr', 'message', 'Latitude'),
(574, '.latitude', 'en', 'message', 'Latitude'),
(575, '.longitude', 'fr', 'message', 'Longitude'),
(576, '.longitude', 'en', 'message', 'Longitude'),
(577, '.kml', 'fr', 'message', 'KML'),
(578, '.kml', 'en', 'message', 'KML'),
(579, '.zoom', 'fr', 'message', 'Zoom'),
(580, '.zoom', 'en', 'message', 'Zoom'),
(581, 'show.the.children', 'fr', 'message', 'Montrer les enfants'),
(582, 'show.the.children', 'en', 'message', 'Show the children'),
(583, '.subtitle', 'fr', 'message', 'Sous-titre'),
(584, '.subtitle', 'en', 'message', 'Subtitle'),
(585, '.author', 'fr', 'message', 'Auteur'),
(586, '.author', 'en', 'message', 'Author'),
(587, '.publisher', 'fr', 'message', 'Éditeur'),
(588, '.publisher', 'en', 'message', 'Publisher'),
(589, '.year', 'fr', 'message', 'Année'),
(590, '.year', 'en', 'message', 'Year'),
(591, '.isbn', 'fr', 'message', 'ISBN'),
(592, '.isbn', 'en', 'message', 'ISBN'),
(593, '.id', 'fr', 'message', 'ID'),
(594, '.id', 'en', 'message', 'ID'),
(595, '.label', 'fr', 'message', 'Étiquette'),
(596, '.label', 'en', 'message', 'Label'),
(597, 'make.french.text', 'fr', 'message', 'Faire du texte en français'),
(598, 'make.french.text', 'en', 'message', 'Make french text'),
(599, 'make.english.text', 'fr', 'message', 'Faire du texte anglais'),
(600, 'make.english.text', 'en', 'message', 'Make english text'),
(602, 'repeat.password', 'fr', 'message', 'Répéter le mot de passe'),
(603, 'repeat.password', 'en', 'message', 'Repeat password'),
(604, '.rolestr', 'fr', 'message', 'Rôles'),
(605, '.rolestr', 'en', 'message', 'Roles'),
(606, '.membership', 'fr', 'message', 'Grade du membre'),
(607, '.membership', 'en', 'message', 'User Level'),
(608, '.surname', 'fr', 'message', 'Nom'),
(609, '.surname', 'en', 'message', 'Surname'),
(610, '.forename', 'fr', 'message', 'Prénom'),
(611, '.forename', 'en', 'message', 'Forename'),
(612, '.alias', 'fr', 'message', 'Alias'),
(613, '.alias', 'en', 'message', 'Alias'),
(614, '.images', 'fr', 'message', 'Images'),
(615, '.images', 'en', 'message', 'Images'),
(616, '.participants', 'fr', 'message', 'Participants'),
(617, '.participants', 'en', 'message', 'Participants'),
(618, '.parent', 'fr', 'message', 'Parent'),
(619, '.parent', 'en', 'message', 'Parent'),
(620, '.locid', 'fr', 'message', 'LocID'),
(621, '.locid', 'en', 'message', 'LocID'),
(622, '.startdate', 'fr', 'message', 'Date de début'),
(623, '.startdate', 'en', 'message', 'Start date'),
(624, '.enddate', 'fr', 'message', 'Date de fin'),
(625, '.enddate', 'en', 'message', 'Enddate'),
(626, 'virtual.museum', 'fr', 'message', 'Musée virtuel'),
(627, 'virtual.museum', 'en', 'message', 'E-museum'),
(628, 'tell.us.your.interest.in.our.s', 'fr', 'message', 'Indiquez les motifs de votre intérêt'),
(629, 'tell.us.your.interest.in.our.s', 'en', 'message', 'Tell us your interest in our site'),
(630, 'tell.us.your.interest.in.our.site', 'fr', 'message', 'Indiquez les motifs de votre intérêt'),
(631, 'tell.us.your.interest.in.our.site', 'en', 'message', 'Why are you interested in our site'),
(632, '.captured', 'fr', 'message', '_.captured'),
(633, '.captured', 'en', 'message', '_.captured'),
(634, 'news.items', 'fr', 'message', 'Les nouvelles du jour'),
(635, 'news.items', 'en', 'message', 'Today\'s news');
