# parameters cloud.yml

parameters:
   
    database_host:  '127.0.0.1'
    database_port: '3306'
    database_name: 'cwckdwxutj'
    database_user: 'cwckdwxutj'
    database_password: 'cheilly'
    
    secret: 56f1c6ae2e2bea4288f04e3c1e67795d5890d3e0

    email-transport: 'smtp'
    email-encryption: ssl 
    email-auth_mode: login
    email-host: mail.lerot.org
    email-port: 465
    email-username:  'admin_fflsas34@lerot.org'
    email-password:  'harrods_1944'
    
    admin-name: "FFLSAS-admin"
    admin-email: "admin_fflsas34@lerot.org"
    kml-folder-long: '%kernel.project_dir%/web/kml/'
    kml-folder: '/kml/'
    new-images-folder: '/newimages/'
    new-images-folder-long: '%kernel.project_dir%/web/newimages/'
    external-images : "http://fflsas.org/images/stories/fflsas/"
