
# config/routing.yml

imageroute : 
   path: /web/newimages


index:
   path: /
   controller: AppBundle\Controller\AccueilController::ShowFrench
   
index_en:
   path: /en/accueil
   controller: AppBundle\Controller\AccueilController::ShowEnglish
   
index_fr:
   path: /fr/accueil
   controller: AppBundle\Controller\AccueilController::showFrench
   
   
accueil:
   path: /accueil
   controller: AppBundle\Controller\AccueilController::Showtest   
   
adminlang:
  path: /{_locale}/adminlang/{oldpath}
  controller: AppBundle\Controller\AdminlangController::Changelang
  requirements:
        _locale: en|fr|FR|EN
   
   
login:
    path: /{_locale}/login
    controller:  AppBundle\Controller\SecurityController::login
    requirements:
        _locale: en|fr|FR|EN
        
        
    
logout:
    path: /logout
    #controller:  AppBundle\Controller\SecurityController::logoutAction      
            
logout_en:
    path: /{_locale}/logout
    requirements:
        _locale: en|fr|FR|EN                  
            
login_check:
    path: /{_locale}/login_check
    controller:  AppBundle\Controller\SecurityController::loginCheckAction
    requirements:
           _locale: en|fr|FR|EN
    
register:
    path: /{_locale}/register
    controller:  AppBundle\Controller\RegistrationController::register    
    requirements:
        _locale: en|fr|FR|EN
        
complete_registration:
    path: /{_locale}/complete/{uid}
    controller:  AppBundle\Controller\RegistrationController::complete   
    requirements:
        _locale: en|fr|FR|EN
        
remote_complete_registration:
    path: /remotecomplete/{uid}/{code}
    controller:  AppBundle\Controller\RegistrationController::remotecomplete   

   
   
#=============================messages==================   
   
message_mail:
    path: /{_locale}/mailto
    controller: AppBundle\Controller\MessageController:createMessage
    requirements:
        _locale: en|fr|FR|EN
        
messages_show_all:
    path: /admin/message/all
    controller: AppBundle\Controller\MessageController:showMessages
   
        
        
message_show_one:
    path: /admin/message/{cid}
    controller: AppBundle\Controller\MessageController:showAdminMessage

message_show_user_one:
    path: /admin/user/{uid}/message/view/{cid}
    controller: AppBundle\Controller\MessageController:showUserMessage
    
message_delete:
    path: /admin/message/delete/{cid}
    controller: AppBundle\Controller\MessageController:deleteMessage
    
message_send:
    path: /admin/message/send/{uid}
    controller: AppBundle\Controller\MessageController:sendMessageToUser
    
#=============================users==================

admin_user_new:
    path: /admin/user/new
    controller:  AppBundle\Controller\UserController::newuser  

    
admin_user_search:
    path: /admin/user/search
    controller:  AppBundle\Controller\UserController::UserSearch     
    
users_editone:
    path: /admin/user/{uid}
    controller:  AppBundle\Controller\UserController:showone
    
user_admin:
    path: /admin/user/edit/{uid}
    controller:  AppBundle\Controller\UserController:editone
    
user_delete:
    path: /admin/user/delete/{uid}
    controller:  AppBundle\Controller\UserController:deleteuser

user_edit:
     path: /{_locale}/user/{uid}
     controller:  AppBundle\Controller\UserController:showuser
     requirements:
        _locale: en|fr|FR|EN
    
user_editdetail:
     path: /{_locale}/useredit/{uid}
     controller:  AppBundle\Controller\UserController:edituser
     requirements:
        _locale: en|fr|FR|EN
        
user_viewmessage:        
      path:  /{_locale}/user/{uid}/viewmessage/{mid}
      controller:  AppBundle\Controller\UserController:viewmessage
      requirements:
        _locale: en|fr|FR|EN
        
user_message_delete:        
      path:  /{_locale}/user/{uid}/message/delete/{mid}
      controller:  AppBundle\Controller\UserController:deletemessage
      requirements:
        _locale: en|fr|FR|EN
        
        

        
#=========================search===============
    
search_all:    
     path: /{_locale}/search/all
     controller:  AppBundle\Controller\SearchController::ShowAll
     requirements:
        _locale: en|fr|FR|EN
        
#==================bookmark

bookmarkdelete:
     path: /admin/bookmark/delete/{blt}/{key}
     controller:  AppBundle\Controller\BookmarkController::delete
     
admin_bookmark_edit:
     path: /admin/bookmark/edit
     controller:  AppBundle\Controller\BookmarkController::Edit     

#===================== Person edit      
        
 
Person_new:
    path: /admin/person/register
    controller: AppBundle\Controller\AdminPersonController::register  

admin_Person_edit_detail:
    path: /admin/person/detail/{pid}
    controller: AppBundle\Controller\AdminPersonController::edit 
    
admin_Person_one:
    path: /admin/person/{pid}
    controller: AppBundle\Controller\AdminPersonController::Editone
    
    
admin_Person_addevent:
# create a participation 
    path: /admin/person/addevent/{pid}/{eid}
    controller: AppBundle\Controller\AdminPersonController::addevent    
    
admin_Person_addimage:
    path: /admin/person/addimage/{pid}/{iid}
    controller: AppBundle\Controller\AdminPersonController::addimage   
    
    
admin_Person_addcontent:
    path: /admin/person/addcontent/{pid}/{cid}
    controller: AppBundle\Controller\AdminPersonController::addcontent     

admin_Person_addlocation:
    path: /admin/person/addlocation/{pid}/{lid}
    controller: AppBundle\Controller\AdminPersonController::addlocation   
    
    
admin_Person_removeimage:
    path: /admin/person/removeimage/{pid}/{iid}
    controller: AppBundle\Controller\AdminPersonController::removeimage   
    
    
admin_Person_bookmark:
    path: /admin/person/addbookmark/{pid}
    controller: AppBundle\Controller\AdminPersonController::addbookmark
   
user_Person_bookmark:
    path: /{_locale}/person/addbookmark/{pid}
    controller: AppBundle\Controller\PersonController::addUserbookmark   
   
removeparticipation:
    path: /admin/person/delete/{pid}/{partid}
   # controller: AppBundle\Controller\AdminPersonController::delete
    defaults: { _controller: AppBundle\Controller\AdminPersonController::deleteAction}
    requirements:
        partid:  \d+

#===================== Person routes  
        
Person_all_locale:
    path: /{_locale}/person/all
    controller:  AppBundle\Controller\PersonController::Showall
    requirements:
        _locale: en|fr|FR|EN
        
Person_one_locale:
    path: /{_locale}/person/{pid}
    controller:  AppBundle\Controller\PersonController::Showone
    requirements:
        _locale: en|fr|FR|EN
        

    
    
#===================participants 
    
participants_all:
     path: /{_locale}/participant/all 
     controller:  AppBundle\Controller\ParticipantController::Showall
     requirements:
        _locale: en|fr|FR|EN
     
participants_one:
     path: /{_locale}/participant/{pid}
     controller:  AppBundle\Controller\ParticipantController::Showone
     requirements:
        _locale: en|fr|FR|EN
     
admin_participants_editone:
    path: /admin/participant/detail/{ptid}
    controller:  AppBundle\Controller\ParticipantController::edit   
     
admin_participants_edit:
    path: /admin/participant/{ptid}
    controller:  AppBundle\Controller\ParticipantController::edit   
    
admin_participant_person:
     path: /admin/participations/editperson/{pid}
     controller:  AppBundle\Controller\ParticipantController::EditPerson

participants_add_person:
    path: /admin/participant/add/{eid}/{pid}
    controller:  AppBundle\Controller\ParticipantController::addparticipant
    

    
    
#===================texts
    
texts_all:
    path: /text/all
    controller:  AppBundle\Controller\TextController::Showall    
    
texts_group:
    path: /text/group
    controller:  AppBundle\Controller\TextController::Showgroup  
   
admin_text_edit:
   path : /admin/text/{objecttype}/{objid}/{attribute}/{language}
   controller:  AppBundle\Controller\TextController::editone   
   
   
text_person_admin:
   path : /admin/text/person/{pid}
   controller:  AppBundle\Controller\TextController::editperson   
   
admin_text_event:
   path : /admin/text/event/{eid}
   controller:  AppBundle\Controller\TextController::editevent   
    
admin_text_image:
    path: /admin/text/image/{iid}   
    controller:  AppBundle\Controller\TextController::editimage   
    
admin_text_reflink:
    path: /admin/text/reflink/{rfid}   
    controller:  AppBundle\Controller\TextController::editreflink 
    

   
texts_edit_group:
   path : /admin/text/{objecttype}/{objid}
   controller:  AppBundle\Controller\TextController::editgroup  

#==============================image=====================
   
admin_image_asearch:
    path : /admin/image/search 
    controller:  AppBundle\Controller\ImageController::Adminsearch      
   
user_image_all:
    path : /{_locale}/image/all 
    controller:  AppBundle\Controller\ImageController::Showall
    requirements:
        _locale: en|fr|FR|EN
        
user_image_one:
    path : /{_locale}/image/{iid}
    controller:  AppBundle\Controller\ImageController::Showone
    requirements:
        _locale: en|fr|EN|FR
        
        
admin_image_addbookmark:
    path:   /admin/image/addBookmark/{iid}
    controller:  AppBundle\Controller\ImageController::addbookmark
                   
admin_image_addref:
    path:   /admin/image/addref/{otype}/{oid}/{iid}
    controller:  AppBundle\Controller\ImageController::addref
    
admin_image_new:
    path: /admin/image/new
    controller:  AppBundle\Controller\ImageController::newimage         
    
        
admin_image_showone:
    path: /admin/image/{iid}
    controller:  AppBundle\Controller\ImageController::editone
           
    
           
        
admin_image_edit:
    path: /admin/image/edit/{iid}
    controller:  AppBundle\Controller\ImageController::edit
    
admin_image_bookmark:
    path: /admin/image/bookmark/{iid}
    controller:  AppBundle\Controller\ImageController::addBookmark

    
user_image_bookmark:
    path: /{_locale}/image/addbookmark/{iid}
    controller:  AppBundle\Controller\ImageController::addUserbookmark
    requirements:
        _locale: en|fr|FR|EN
    
#=============================events
    
events_admin_top:
    path: /admin/event/top
    controller: AppBundle\Controller\AdminEventController::Showtop
  
events_admin_addbookmark:
    path:  /admin/event/addbookmark/{eid}
    controller: AppBundle\Controller\AdminEventController::addBookmark  
    
events_user_addbookmark:
    path:  /{_locale}/event/addbookmark/{eid}
    controller: AppBundle\Controller\EventController::addBookmark  
    requirements:
        _locale: en|fr|FR|EN
        
events_admin_addimage:
    path:  /admin/event/addimage/{eid}/{iid}
    controller: AppBundle\Controller\AdminEventController::addImage  
  
event_admin_removeimage:
     path: /admin/event/removeimage/{eid}/{irid}
     controller: AppBundle\Controller\AdminEventController::removeImageRef  
     
event_admin_setlocation:     
     path: /admin/event/setlocation/{eid}/{lid}
     controller: AppBundle\Controller\AdminEventController::setLocation  
      
      
events_admin_participants:
    path:  /admin/event/participant/{eid}
    controller: AppBundle\Controller\AdminEventController::Editparticipants
  
    
events_admin_addparticipant:
    path:  /admin/event/addparticipant/{eid}/{pid}
    controller: AppBundle\Controller\AdminEventController::addparticipant
    
events_admin_addcontent:
    path:  /admin/event/addcontent/{eid}/{cid}
    controller: AppBundle\Controller\AdminEventController::addcontent   
    
events_all:
    path:  /{_locale}/event/all
    controller:  AppBundle\Controller\EventController::Showall    
    
events_top_locale:
    path: /{_locale}/event/top
    controller:  AppBundle\Controller\EventController::Showtop
    requirements:
        _locale: en|fr|FR|EN
        
events_top:
    path: /{_locale}/event/top
    controller:  AppBundle\Controller\EventController::Showtop
  
events_one:
    path:  /{_locale}/event/{eid}
    controller:  AppBundle\Controller\EventController::Showone    
    requirements:
        _locale: en|fr|FR|EN
        
        
admin_events_one:
    path:  /admin/event/{eid}
    controller: AppBundle\Controller\AdminEventController::Editone 
    
admin_event_one:
    path:  /admin/event/{eid}
    controller: AppBundle\Controller\AdminEventController::Editone 
    
admin_events_detail:
    path:  /admin/event/detail/{eid}
    controller: AppBundle\Controller\AdminEventController::Editdetail 
        
#======================incidents
    
incident_one:
    path : /{_locale}/incident/{inid} 
    controller:  AppBundle\Controller\IncidentController::Showone    
    requirements:
        _locale: en|fr|FR|EN
        
        
admin_incidents_all:
    path : /admin/incident/all 
    controller:  AppBundle\Controller\IncidentController::Showall
   
admin_incident_new:
    path : /admin/incident/new/{eid}/{pid}
    controller:  AppBundle\Controller\IncidentController::new
    
    
admin_incidents_edit:
    path : /admin/incident/{inid} 
    controller:  AppBundle\Controller\IncidentController::edit
    
admin_incident_delete:
    path : /admin/incident/delete/{inid} 
    controller:  AppBundle\Controller\IncidentController::delete




#=======================location===================

location_top:
    path: /location/top
    controller:  AppBundle\Controller\LocationController::Showtop  
    
location_all:
    path : /location/all 
    controller:  AppBundle\Controller\LocationController::Showall
    
admin_location_upload:    
    path: /admin/location/upload/{lid}
    controller:  AppBundle\Controller\LocationController::upload
    
admin_location_bookmark:
    path: /admin/location/addbookmark/{lid}
    controller:  AppBundle\Controller\LocationController::addbookmark
    
user_location_bookmark:
    path: /{_locale}/location/addbookmark/{lid}
    controller:  AppBundle\Controller\LocationController::addUserbookmark
    requirements:
        _locale: en|fr|FR|EN

 
 
admin_location_top:
    path: /admin/location/top
    controller:  AppBundle\Controller\LocationController::Edittop  
    
admin_location_editone:
    path: /admin/location/{lid}
    controller:  AppBundle\Controller\LocationController::Editone  
    
    
location_new:
    path: /admin/location/detail/new/{rid}
    controller:  AppBundle\Controller\LocationController::New
    
admin_location_edit_detail:
    path: /admin/location/detail/{lid}
    controller:  AppBundle\Controller\LocationController::Edit
    


location_one:
    path: /{_locale}/location/{lid}
    controller:  AppBundle\Controller\LocationController::Showone  
    requirements:
        _locale: en|fr|FR|EN
    



#======================linkrefs ======================

linkref_all:
    path : /admin/linkref/all 
    controller:  AppBundle\Controller\LinkrefController::Showall
    
linkref_one:
    path : /linkref/{rid} 
    controller:  AppBundle\Controller\LinkrefController::Showone  
    

    
linkref_edit_detail:
    path : /admin/linkref/edit/{ot}/{oid}/{lrid} 
    controller:  AppBundle\Controller\LinkrefController::Edit
    
linkref_delete_one:    
    path : /admin/linkref/delete/{ot}/{oid}/{lrid} 
    controller:  AppBundle\Controller\LinkrefController::Delete
    
    
linkref_edit:
    path : /admin/linkref/{ot}/{oid}/{lrid} 
    controller:  AppBundle\Controller\LinkrefController::Editone
    
linkref_edit_person_group:
   path : /admin/linkref/editperson/{pid}
   controller:  AppBundle\Controller\LinkrefController::EditpersonGroup  
   
linkref_edit_event_group:
   path : /admin/linkref/editevent/{eid}
   controller:  AppBundle\Controller\LinkrefController::EditeventGroup  
   
   
linkref_add:
   path : /admin/addref/{otype1}/{oid1}/{otype2}/{oid2}
   controller:  AppBundle\Controller\LinkrefController::Addlink  
   
#====================content====================================

content_all:
    path: /{_locale}/content/all
    controller:  AppBundle\Controller\ContentController::Showall  
    requirements:
        _locale: en|fr|FR|EN
        
content_one:
    path: /{_locale}/content/{sid}
    controller:  AppBundle\Controller\ContentController::Showsubject  
    requirements:
        _locale: en|fr|FR|EN
        
content_menu:
    path: /{_locale}/menucontent/{sid}
    controller:  AppBundle\Controller\ContentController::Showsubjet 
    requirements:
        _locale: en|fr|FR|EN
        
subject_one:
    path: /{_locale}/contentid/{cid}
    controller:  AppBundle\Controller\ContentController::Showcontent  
    requirements:
        _locale: en|fr|FR|EN
        
admin_content_search:
    path: /admin/content/search
    controller:  AppBundle\Controller\ContentController::ContentSearch  

admin_content_edit:
    path: /admin/content/edit/{cid}
    controller:  AppBundle\Controller\ContentController::Edit   
    
admin_content_newt:
    path: /admin/content/new/
    controller:  AppBundle\Controller\ContentController::Editnew   
    
admin_content_delete:
    path: /admin/content/delete/{cid}
    controller:  AppBundle\Controller\ContentController::Delete       
    
admin_content_bookmark:    
    path:  /admin/content/addbookmark/{sid}
    controller:  AppBundle\Controller\ContentController::addBookmark  
    
user_content_bookmark:    
    path:  /{_locale}/content/addbookmark/{sid}
    controller:  AppBundle\Controller\ContentController::addUserBookmark  
    
    
admin_content_editone:
    path: /admin/content/{sid}
    controller:  AppBundle\Controller\ContentController::Editsubject
    
admin_content_new:    
    path: /admin/content/edit/{sid}/{lang}
    controller:  AppBundle\Controller\ContentController::Newlang
    
admin_content_deleteimage:
    path:  /admin/content/deleteimage/{cid}/{isn}
    controller:  AppBundle\Controller\ContentController::Deleteimage  
    
   
    
    
#=========================================================
    
catch_all:
    path: /{catch_all}
    controller: AppBundle\Controller\AccueilController::Showall
    
