security:

    encoders:
      #Symfony\Component\Security\Core\User\User:
         AppBundle\Entity\User:  
            algorithm: bcrypt
      

    providers:
          
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             pattern:    ^/
             anonymous: ~
            # http_basic: ~
             provider: our_db_provider
             #access_denied_handler: AppBundle\Security\AccessDeniedHandler
             form_login: 
               login_path: login
               check_path: login
               default_target_path: /fr/accueil
    #            always_use_default_target_path: 1
        #secured_area:
            # ...
             logout:
                path:   /logout
                target: /fr/accueil                    
            
            # remember_me:
             #   secret:   '%kernel.secret%'
            #    lifetime: 604800 # 1 week in seconds
            #    path:     /
 
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/symfonyimages, roles:  IS_AUTHENTICATED_ANONYMOUSLY } 
         - { path: ^/register, roles:  IS_AUTHENTICATED_ANONYMOUSLY } 
         - { path: ^/linkref/, roles: ROLE_USER } 
         - { path: ^/(fr|en|FR|EN)/incidents/, roles:  IS_AUTHENTICATED_ANONYMOUSLY} 
         - { path: ^/(fr|en|FR|EN)/menucontent/, roles:  IS_AUTHENTICATED_ANONYMOUSLY} 
         - { path: ^/(fr|en|FR|EN)/images, roles: ROLE_USER }  
         - { path: ^/(fr|en|FR|EN)/content, roles: ROLE_USER }  
         - { path: ^/(fr|en|FR|EN)/search, roles: ROLE_USER }
         - { path: ^/(fr|en|FR|EN)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/(fr|en|FR|EN), roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_ADMIN  }
        
