<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appDevDebugProjectContainerUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes;

    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
        if (null === self::$declaredRoutes) {
            self::$declaredRoutes = array(
        '_wdt' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:toolbarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_wdt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:homeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_bar' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchBarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search_bar',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_phpinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:phpinfoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/phpinfo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_results' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchResultsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/search/results',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_open_file' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:openAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/open',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_router' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.router:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/router',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception_css' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:cssAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception.css',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_twig_error_test' => array (  0 =>   array (    0 => 'code',    1 => '_format',  ),  1 =>   array (    '_controller' => 'twig.controller.preview_error:previewErrorPageAction',    '_format' => 'html',  ),  2 =>   array (    'code' => '\\d+',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => '[^/]++',      3 => '_format',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'code',    ),    2 =>     array (      0 => 'text',      1 => '/_error',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'imageroute' => array (  0 =>   array (  ),  1 =>   array (  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/web/newimages',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AccueilController::ShowFrench',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'index_en' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AccueilController::ShowEnglish',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/en/accueil',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'index_fr' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AccueilController::showFrench',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/fr/accueil',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'accueil' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AccueilController::Showtest',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/accueil',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adminlang' => array (  0 =>   array (    0 => '_locale',    1 => 'oldpath',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminlangController::Changelang',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oldpath',    ),    1 =>     array (      0 => 'text',      1 => '/adminlang',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'login' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\SecurityController::login',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'logout' => array (  0 =>   array (  ),  1 =>   array (  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'logout_en' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'login_check' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\SecurityController::loginCheckAction',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'register' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\RegistrationController::register',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'complete_registration' => array (  0 =>   array (    0 => '_locale',    1 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\RegistrationController::complete',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/complete',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'remote_complete_registration' => array (  0 =>   array (    0 => 'uid',    1 => 'code',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\RegistrationController::remotecomplete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'code',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    2 =>     array (      0 => 'text',      1 => '/remotecomplete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'message_mail' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:createMessage',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/mailto',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'messages_show_all' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:showMessages',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/message/all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'message_show_one' => array (  0 =>   array (    0 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:showAdminMessage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/message',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'message_show_user_one' => array (  0 =>   array (    0 => 'uid',    1 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:showUserMessage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/message/view',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    3 =>     array (      0 => 'text',      1 => '/admin/user',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'message_delete' => array (  0 =>   array (    0 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:deleteMessage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/message/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'message_send' => array (  0 =>   array (    0 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\MessageController:sendMessageToUser',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/message/send',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_user_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController::newuser',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/user/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_user_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController::UserSearch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/user/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'users_editone' => array (  0 =>   array (    0 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:showone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/user',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_admin' => array (  0 =>   array (    0 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/user/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_delete' => array (  0 =>   array (    0 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:deleteuser',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/user/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_edit' => array (  0 =>   array (    0 => '_locale',    1 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:showuser',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/user',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_editdetail' => array (  0 =>   array (    0 => '_locale',    1 => 'uid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:edituser',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    1 =>     array (      0 => 'text',      1 => '/useredit',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_viewmessage' => array (  0 =>   array (    0 => '_locale',    1 => 'uid',    2 => 'mid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:viewmessage',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mid',    ),    1 =>     array (      0 => 'text',      1 => '/viewmessage',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    3 =>     array (      0 => 'text',      1 => '/user',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_message_delete' => array (  0 =>   array (    0 => '_locale',    1 => 'uid',    2 => 'mid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\UserController:deletemessage',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'mid',    ),    1 =>     array (      0 => 'text',      1 => '/message/delete',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'uid',    ),    3 =>     array (      0 => 'text',      1 => '/user',    ),    4 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'search_all' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\SearchController::ShowAll',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/search/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'bookmarkdelete' => array (  0 =>   array (    0 => 'blt',    1 => 'key',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\BookmarkController::delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'key',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'blt',    ),    2 =>     array (      0 => 'text',      1 => '/admin/bookmark/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_bookmark_edit' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\BookmarkController::Edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/bookmark/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'Person_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::register',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/person/register',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_edit_detail' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/person/detail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_one' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::Editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/person',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_addevent' => array (  0 =>   array (    0 => 'pid',    1 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::addevent',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/addevent',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_addimage' => array (  0 =>   array (    0 => 'pid',    1 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::addimage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/addimage',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_addcontent' => array (  0 =>   array (    0 => 'pid',    1 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::addcontent',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/addcontent',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_addlocation' => array (  0 =>   array (    0 => 'pid',    1 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::addlocation',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/addlocation',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_removeimage' => array (  0 =>   array (    0 => 'pid',    1 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::removeimage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/removeimage',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_Person_bookmark' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::addbookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/person/addbookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_Person_bookmark' => array (  0 =>   array (    0 => '_locale',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\PersonController::addUserbookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/person/addbookmark',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'removeparticipation' => array (  0 =>   array (    0 => 'pid',    1 => 'partid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminPersonController::deleteAction',  ),  2 =>   array (    'partid' => '\\d+',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'partid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/person/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'Person_all_locale' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\PersonController::Showall',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/person/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'Person_one_locale' => array (  0 =>   array (    0 => '_locale',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\PersonController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/person',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'Person_pdf_one' => array (  0 =>   array (    0 => '_locale',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\PersonController::pdfone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/person/pdf',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'participants_all' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::Showall',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/participant/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'participants_one' => array (  0 =>   array (    0 => '_locale',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/participant',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_participants_editone' => array (  0 =>   array (    0 => 'ptid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'ptid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/participant/detail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_participants_edit' => array (  0 =>   array (    0 => 'ptid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'ptid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/participant',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_participant_person' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::EditPerson',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/participations/editperson',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'participants_add_person' => array (  0 =>   array (    0 => 'eid',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ParticipantController::addparticipant',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/participant/add',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'texts_all' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/text/all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'texts_group' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::Showgroup',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/text/group',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_text_edit' => array (  0 =>   array (    0 => 'objecttype',    1 => 'objid',    2 => 'attribute',    3 => 'language',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'language',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'attribute',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'objid',    ),    3 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'objecttype',    ),    4 =>     array (      0 => 'text',      1 => '/admin/text',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'text_person_admin' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editperson',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/text/person',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_text_event' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editevent',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/text/event',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_text_image' => array (  0 =>   array (    0 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editimage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/text/image',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_text_reflink' => array (  0 =>   array (    0 => 'rfid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editreflink',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'rfid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/text/reflink',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'texts_edit_group' => array (  0 =>   array (    0 => 'objecttype',    1 => 'objid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\TextController::editgroup',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'objid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'objecttype',    ),    2 =>     array (      0 => 'text',      1 => '/admin/text',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_asearch' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::Adminsearch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/image/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_image_all' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::Showall',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/image/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_image_one' => array (  0 =>   array (    0 => '_locale',    1 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|EN|FR',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/image',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|EN|FR',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_addbookmark' => array (  0 =>   array (    0 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::addbookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/image/addBookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_addref' => array (  0 =>   array (    0 => 'otype',    1 => 'oid',    2 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::addref',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'otype',    ),    3 =>     array (      0 => 'text',      1 => '/admin/image/addref',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::newimage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/image/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_showone' => array (  0 =>   array (    0 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/image',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_edit' => array (  0 =>   array (    0 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/image/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_image_bookmark' => array (  0 =>   array (    0 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::addBookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/image/bookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_image_bookmark' => array (  0 =>   array (    0 => '_locale',    1 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ImageController::addUserbookmark',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'text',      1 => '/image/addbookmark',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_top' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::Showtop',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/event/top',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_addbookmark' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::addBookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/event/addbookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_user_addbookmark' => array (  0 =>   array (    0 => '_locale',    1 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\EventController::addBookmark',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/event/addbookmark',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_addimage' => array (  0 =>   array (    0 => 'eid',    1 => 'iid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::addImage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'iid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/event/addimage',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'event_admin_removeimage' => array (  0 =>   array (    0 => 'eid',    1 => 'irid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::removeImageRef',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'irid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/event/removeimage',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'event_admin_setlocation' => array (  0 =>   array (    0 => 'eid',    1 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::setLocation',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/event/setlocation',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_participants' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::Editparticipants',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/event/participant',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_addparticipant' => array (  0 =>   array (    0 => 'eid',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::addparticipant',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/event/addparticipant',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_admin_addcontent' => array (  0 =>   array (    0 => 'eid',    1 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::addcontent',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/event/addcontent',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_all' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\EventController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/event/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_top_locale' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\EventController::Showtop',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/event/top',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_top' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\EventController::Showtop',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/event/top',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'events_one' => array (  0 =>   array (    0 => '_locale',    1 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\EventController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/event',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_events_one' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::Editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/event',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_event_one' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::Editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/event',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_events_detail' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AdminEventController::Editdetail',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/event/detail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'incident_one' => array (  0 =>   array (    0 => '_locale',    1 => 'inid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\IncidentController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'inid',    ),    1 =>     array (      0 => 'text',      1 => '/incident',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_incidents_all' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\IncidentController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/incident/all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_incident_new' => array (  0 =>   array (    0 => 'eid',    1 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\IncidentController::new',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/incident/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_incidents_edit' => array (  0 =>   array (    0 => 'inid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\IncidentController::edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'inid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/incident',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_incident_delete' => array (  0 =>   array (    0 => 'inid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\IncidentController::delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'inid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/incident/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'location_top' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Showtop',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/location/top',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'location_all' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/location/all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_location_upload' => array (  0 =>   array (    0 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::upload',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/location/upload',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_location_bookmark' => array (  0 =>   array (    0 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::addbookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/location/addbookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_location_bookmark' => array (  0 =>   array (    0 => '_locale',    1 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::addUserbookmark',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/location/addbookmark',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_location_top' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Edittop',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/location/top',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_location_editone' => array (  0 =>   array (    0 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/location',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'location_new' => array (  0 =>   array (    0 => 'rid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::New',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'rid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/location/detail/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_location_edit_detail' => array (  0 =>   array (    0 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/location/detail',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'location_one' => array (  0 =>   array (    0 => '_locale',    1 => 'lid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LocationController::Showone',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lid',    ),    1 =>     array (      0 => 'text',      1 => '/location',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_all' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/linkref/all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_one' => array (  0 =>   array (    0 => 'rid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Showone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'rid',    ),    1 =>     array (      0 => 'text',      1 => '/linkref',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_edit_detail' => array (  0 =>   array (    0 => 'ot',    1 => 'oid',    2 => 'lrid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lrid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'ot',    ),    3 =>     array (      0 => 'text',      1 => '/admin/linkref/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_delete_one' => array (  0 =>   array (    0 => 'ot',    1 => 'oid',    2 => 'lrid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lrid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'ot',    ),    3 =>     array (      0 => 'text',      1 => '/admin/linkref/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_edit' => array (  0 =>   array (    0 => 'ot',    1 => 'oid',    2 => 'lrid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Editone',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lrid',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'ot',    ),    3 =>     array (      0 => 'text',      1 => '/admin/linkref',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_edit_person_group' => array (  0 =>   array (    0 => 'pid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::EditpersonGroup',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'pid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/linkref/editperson',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_edit_event_group' => array (  0 =>   array (    0 => 'eid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::EditeventGroup',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'eid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/linkref/editevent',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'linkref_add' => array (  0 =>   array (    0 => 'otype1',    1 => 'oid1',    2 => 'otype2',    3 => 'oid2',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\LinkrefController::Addlink',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid2',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'otype2',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'oid1',    ),    3 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'otype1',    ),    4 =>     array (      0 => 'text',      1 => '/admin/addref',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'content_all' => array (  0 =>   array (    0 => '_locale',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Showall',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/content/all',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'content_one' => array (  0 =>   array (    0 => '_locale',    1 => 'sid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Showsubject',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    1 =>     array (      0 => 'text',      1 => '/content',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'content_menu' => array (  0 =>   array (    0 => '_locale',    1 => 'sid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Showsubject',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    1 =>     array (      0 => 'text',      1 => '/menucontent',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'subject_one' => array (  0 =>   array (    0 => '_locale',    1 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Showcontent',  ),  2 =>   array (    '_locale' => 'en|fr|FR|EN',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/contentid',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => 'en|fr|FR|EN',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::ContentSearch',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/content/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_edit' => array (  0 =>   array (    0 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Edit',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/content/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_newt' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Editnew',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/admin/content/new/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_delete' => array (  0 =>   array (    0 => 'cid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Delete',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/content/delete',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_bookmark' => array (  0 =>   array (    0 => 'sid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::addBookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/content/addbookmark',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_content_bookmark' => array (  0 =>   array (    0 => '_locale',    1 => 'sid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::addUserBookmark',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    1 =>     array (      0 => 'text',      1 => '/content/addbookmark',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => '_locale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_editone' => array (  0 =>   array (    0 => 'sid',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Editsubject',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    1 =>     array (      0 => 'text',      1 => '/admin/content',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_new' => array (  0 =>   array (    0 => 'sid',    1 => 'lang',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Newlang',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'lang',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'sid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/content/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'admin_content_deleteimage' => array (  0 =>   array (    0 => 'cid',    1 => 'isn',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\ContentController::Deleteimage',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'isn',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'cid',    ),    2 =>     array (      0 => 'text',      1 => '/admin/content/deleteimage',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'catch_all' => array (  0 =>   array (    0 => 'catch_all',  ),  1 =>   array (    '_controller' => 'AppBundle\\Controller\\AccueilController::Showall',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'catch_all',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
    );
        }
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }
}
